version: '3'
services:
  tipdb:
    restart: always
    image: yiluxiangbei/centos7-tipdm-db:20201112
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/server/pg_data/data:/var/lib/postgresql/data/pgdata
  tipdm:
    image: yiluxiangbei/centos7-tipdm:20201112
    privileged: true
    ports:
      - "8083:8082"
      - "8080:8080"
      - "9021:9020"
    depends_on:
      - tipdb
    restart: always